# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-01 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetsapp', '0005_software'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='机房名称')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 't_idc',
                'verbose_name': '机房',
                'verbose_name_plural': '机房',
            },
        ),
    ]
