# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-01 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetsapp', '0009_auto_20180901_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='标签名')),
                ('c_day', models.DateField(auto_now_add=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '标签',
                'db_table': 't_tag',
                'verbose_name': '标签',
            },
        ),
    ]
