# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-01 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetsapp', '0010_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, to='assetsapp.Tag', verbose_name='标签'),
        ),
    ]
