# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-01 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetsapp', '0011_asset_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_model', models.CharField(blank=True, max_length=128, null=True, verbose_name='CPU型号')),
                ('cpu_count', models.PositiveSmallIntegerField(default=1, verbose_name='物理CPU个数')),
                ('cpu_core_count', models.PositiveSmallIntegerField(default=1, verbose_name='CPU核数')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assetsapp.Asset')),
            ],
            options={
                'verbose_name': 'CPU',
                'db_table': 't_cpu',
                'verbose_name_plural': 'CPU',
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='SN号')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='内存型号')),
                ('manufacturer', models.CharField(blank=True, max_length=128, null=True, verbose_name='内存制造商')),
                ('slot', models.CharField(max_length=64, verbose_name='插槽')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='内存大小(GB)')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetsapp.Asset')),
            ],
            options={
                'verbose_name': '内存',
                'db_table': 't_ram',
                'verbose_name_plural': '内存',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ram',
            unique_together=set([('asset', 'slot')]),
        ),
    ]
