# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-01 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetsapp', '0016_newassetapprovalzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='new_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assetsapp.NewAssetApprovalZone'),
        ),
    ]
